# Saving & Loading Bounding Box

**Save Bbox** \
BboxTools uses numpy to save a bounding box. BboxTools provides method to convert a bbox or a list of bboxs to a numpy array, as well as method to load from converted array. Thus, you could using numpy.save() to save bboxs as npy or npz files. 

In [1]:
import numpy as np
import BboxTools as bbt

In [2]:
# Create a bbox
box0 = bbt.Bbox2D([(2, 5), (3, 6)], image_boundary=(8, 8))
print(box0)

<class "Bbox2D", shape=[(2, 5), (3, 6)], boundary=[8, 8]>


In [3]:
# Convert this bbox to numpy
# Notice that the default sort is (y0, y1, x0, x1, boundary0, boundary1)
print(box0.numpy())

[2. 5. 3. 6. 8. 8.]


In [4]:
# A bbox without bounary will give a array with shape (4, )
print(box0.copy().remove_boundary().numpy())

[2. 5. 3. 6.]


BboxTools have function list_box_to_numpy to convert list of bbox to a 2d ndarray. You could enable or disable save_image_boundary, that will return an array with (n, 6) if enabled, (n, 4) otherwise. Notice the default setting of save_image_boundary is False. Also notice enable save_image_boundary requires all the boxes in this list to have boundary, otherwise, it will raise a error.

In [5]:
# Convert a list of bboxs
box_list = [box0, box0.pad(2), box0.shift((1, 2)).set_boundary((9, 9))]
box_array = bbt.list_box_to_numpy(box_list, save_image_boundary=True)
print(box_array)

[[2. 5. 3. 6. 8. 8.]
 [0. 7. 1. 8. 8. 8.]
 [3. 6. 5. 8. 9. 9.]]


Then to save this array, you can using np.save('name_to_file.npy', box_array)

**Load Bbox** \
To load bbox from file, you need firstly load the file to np.ndarry, which can be done by box_array = np.load('name_to_file.npy'). Then you can convert it to a bbox (if the array is 1D) or list of bboxs (if the array is 2D) via bbt.from_numpy(). The default sorts is (y0, y1, x0, x1), however, if you want to load from other source that have a different defination of bbox, you could change it via parameter sorts. Also, this function will automatically load boundary if axis(-1) is equal or large then 6, which is controled by load_boundary_if_possible (default True).

In [6]:
# Load bbox from 1D array
print(bbt.from_numpy(np.array([2, 5, 3, 6])))

# Change sorts (default sorts in pillow)
print(bbt.from_numpy(np.array([3, 2, 6, 5]), sorts=('x0', 'y0', 'x1', 'y1')))

# Also load the image boundary
print(bbt.from_numpy(np.array([2, 5, 3, 6, 8, 8])))

<class "Bbox2D", shape=[(2, 5), (3, 6)]>
<class "Bbox2D", shape=[(2, 5), (3, 6)]>
<class "Bbox2D", shape=[(2, 5), (3, 6)], boundary=[8, 8]>


In [7]:
# Load bbox from 2D array
print(bbt.from_numpy(box_array))

[<class "Bbox2D", shape=[(2, 5), (3, 6)], boundary=[8, 8]>, <class "Bbox2D", shape=[(0, 7), (1, 8)], boundary=[8, 8]>, <class "Bbox2D", shape=[(3, 6), (5, 8)], boundary=[9, 9]>]
